### ISSUE TITLE
Support for version 2.0.X ?

### ISSUE THREAD

**Issue by paulwaldmann** [Hosting-MP/blesta-froxlor#1]
Hi there,

saw your plugin on the blesta forum. Is this repo still maintained? 

Please let me know if there's support for version 2.0.X and if not, what needs to be done to make it work?

Cheers

**Comment by TimoStramann** [comment]
Sorry for no update here. Yes, it's still maintained. I've updated the module to work with the latest Froxlor version as well as the latest Blesta version. However, Froxlor v2 now has stronger security build in (cors validation) but you cannot generate single-sign-on links and thus an additional file needs to be places in the Froxlor install directory as gateway for single-sign-on.  
https://github.com/Hosting-MP/blesta-froxlor/releases/tag/2.0.0  
  
The ansible installer will be updated in the next weeks.

**Comment by TimoStramann** [comment]
With the latest update to [v2.0.1](https://github.com/Hosting-MP/blesta-froxlor/releases/tag/2.0.1), the gateway file isn't required anymore.
